# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci
# sequence whose values do not exceed four million, find the sum of the even-valued terms.


def main(max_number: int = 4000000, divide = 2):
    one, two = 1, 2
    end_list = []
    while two < max_number: 
        if two % divide == 0: 
            end_list.append(two)
        one, two = two, one + two 
    return sum(end_list)
